### ISSUE TITLE
Not displaying on Ipad

### ISSUE THREAD

**Issue by oyvindth** [tommyjlong/platinum-weather-card#3]
**Checklist:**

- [x ] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:2024.8.2**

**Last working release (if known):2024.7.4**

**Browser and Operating System: iPAD app IOS 17.6.1**

**Description of problem:**

The card displays correct in browsers, and in the iPhone app, but in the iPad app it will not display. Have tried multiple iPads, and cleare cache and reinstalled app.

**Comment by joewesch** [comment]
I had a similar issue, but it wasn't working for one of my Pis running chromium-browser. I also upgraded to 2024.8.2 originally and rolling back to 2024.7.4 fixed it for now.

**Comment by bluediamond1984** [comment]
There are more reports with the same issue and also custom cards https://github.com/home-assistant/iOS/issues/2908. Updating the companion app fixed it for me.

**Comment by tommyjlong** [comment]
This is actually not a platinum-weather-card problem, as it is more related to how the front-end presents itself to browsers and companion Apps. I just upgraded to iPAD companion App to 2024.8 and it now works.  I'm closing this.
